<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="MSTest.Sdk"/>
        <PackageReference Include="MSTest.TestFramework"/>
        <PackageReference Include="MSTest.TestAdapter">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/EmberTrace/EmberTrace.csproj"/>
        <ProjectReference Include="../../src/EmberTrace.Abstractions/EmberTrace.Abstractions.csproj"/>
        <ProjectReference Include="../../src/EmberTrace.Analysis/EmberTrace.Analysis.csproj"/>
        <ProjectReference Include="../../src/EmberTrace.Generator/EmberTrace.Generator.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
